export const data = [
    {
        id: "1",
        cover: "https://images.unsplash.com/photo-1624298357597-fd92dfbec01d?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=250&q=80",
        name: "Robert Wolfkisser",
        author: "Engineer",
        dop: new Date(), 
        genre: "Fiction",
        totalCopies: 10,
        availableCopies: 5,
    },
    {
        id: "2",
        cover: "https://images.unsplash.com/photo-1624298357597-fd92dfbec01d?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=250&q=80",
        name: "Twilight",
        author: "author2",
        dop: new Date(), 
        genre: "Fiction",
        totalCopies: 25,
        availableCopies: 20,
    },
    {
        id: "3",
        cover: "https://images.unsplash.com/photo-1624298357597-fd92dfbec01d?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=250&q=80",
        name: "Harry Potter and the Philosopher's Stone",
        author: "Engineer",
        dop: new Date(), 
        genre: "Fiction",
        totalCopies: 30,
        availableCopies: 10,
    },
    {
        id: "4",
        cover: "https://images.unsplash.com/photo-1624298357597-fd92dfbec01d?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=250&q=80",
        name: "Harry Potter and the Chamber of Secrets",
        author: "Engineer",
        dop: new Date(), 
        genre: "Fiction",
        totalCopies: 50,
        availableCopies: 0,
    },
];