export const data = [
    {
        id: '1',
        name: 'The Lord of the Rings',
        author: 'J. R. R. Tolkien',
        genre: 'Fantasy',
        dop: new Date('1954-07-29'),
        availableCopies: 5,
    },
    {
        id: '2',
        name: 'The Hobbit',
        author: 'J. R. R. Tolkien',
        genre: 'Fantasy',
        dop: new Date('1937-09-21'),
        availableCopies: 5,
    },
    {
        id: '3',
        name: 'Harry Potter and the Philosopher\'s Stone',
        author: 'J. K. Rowling',
        genre: 'Fantasy',
        dop: new Date('1997-06-26'),
        availableCopies: 5,
    },
    {
        id: '4',
        name: 'Harry Potter and the Chamber of Secrets',
        author: 'J. K. Rowling',
        genre: 'Fantasy',
        dop: new Date('1998-07-02'),
        availableCopies: 5,
    },
    {
        id: '5',
        name: 'Harry Potter and the Prisoner of Azkaban',
        author: 'J. K. Rowling',
        genre: 'Fantasy',
        dop: new Date('1999-07-08'),
        availableCopies: 5,
    },
    {
        id: '6',
        name: 'Pride and Prejudice',
        author: 'Jane Austen',
        genre: 'Romance',
        dop: new Date('1813-01-28'),
        availableCopies: 5,
    },
    {
        id: '7',
        name: 'To Kill a Mockingbird',
        author: 'Harper Lee',
        genre: 'Novel',
        dop: new Date('1960-07-11'),
        availableCopies: 5,
    },
    {
        id: '8',
        name: 'The Great Gatsby',
        author: 'F. Scott Fitzgerald',
        genre: 'Novel',
        dop: new Date('1925-04-10'),
        availableCopies: 5,
    },
    {
        id: '9',
        name: 'The Catcher in the Rye',
        author: 'J. D. Salinger',
        genre: 'Novel',
        dop: new Date('1951-07-16'),
        availableCopies: 5,
    },
    {
        id: '10',
        name: 'war and peace',
        author: 'Leo Tolstoy',
        genre: 'Novel',
        dop: new Date('1869-01-01'),
        availableCopies: 5,
    },
];